### ISSUE TITLE
[DMP 2024]: Implement Kubernetes Operator for Mifos/Fineract and/or PH-EE

### ISSUE THREAD

**Issue by DavidH-1** [openMF/ph-ee-env-labs#262]
## Description
The goal of this project is to improve the deployability of key projects of our stack like Mifos/Fineract and Payment Hub EE.
Kubernetes operators give kubernetes application dev/ops a great deal of reliability and architectural control over kubernetes applications deployments. Reference[ Operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) for details on the benefits of Kubernetes operators. The benefits of Kubernetes operators can also be quite tangible and visibile by looking  at those under development from peer projects in the financial inclusion space like Mojaloop vNext whom are building out a Kubernetes operator as a means to improve quality, simplify deployment, and improve reliability and testing.

## Goals

- [1] [Gather learnings around Kubernetes operators and their patterns in general (i.e. Monga, Kafka, etc]
- [2] [Design Kubernetes operator based on the above learnings ]
- [3] [Identify what to move from existing Helm chart to Operator ]
- [4] [Implement operator and implement a small helm chart to deploy the operator itself]
- [5] [Project Documentation]
- [6] [Goal - Design and Implement Kubernetes Operator that replaces helm chart and provide a small helm chart for deployment of operator]

### Expected Outcome

DevOps and Sys Admins running our projects would experience a more simplified deployment with greater degree of control, improved quality of their builds and greater reliability and ease of testing. 

### Implementation Details

Mifos PH-EE Kubernetes Operator 

Tech Skills Needed
Docker, Kubernetes, Jenkins, Bash, Java - Spring, PostgreSQL, MariaDB, Cassandra, TDD With JUnit 4, Gradle

### Product Name

Mifos PH-EE Kubernetes Operator 

### Organisation Name

The Mifos Initiative

### Domain

Financial Inclusion

### Tech Skills Needed

Docker, Java, Jenkins, Kubernetes, Spring Boot, Other

### Mentor(s)

@tdaly61

### Category

Backend, CI/CD, Delpoyment, Other

**Comment by NEGRAH-S** [comment]
@DavidH-1 @tdaly61 ,  i am highly interested to work on this project. I was a selected contributor for last year cohort of C4GT , as per me the following are to be done:
- Design the architecture and functionality of the Mifos PH-EE Kubernetes operator.
- Identify components from existing Helm charts suitable for migration to the operator.
- Develop and implement the Kubernetes operator using Docker, Java, Spring Boot, and other relevant technologies.

**Comment by AieshaShetty** [comment]
Hi @tdaly61, I would like to work on this project. My tech stack includes core Java, Spring Boot, and JPA. Is there any smaller issue to work on this first?

**Comment by AbhimanyuSamagra** [comment]
Do not ask process related questions about how to apply and who to contact in the above ticket. The only questions allowed are about technical aspects of the project itself. If you want help with the process, you can refer instructions listed on [Unstop](https://unstop.com/competitions/dedicated-mentoring-program-dmp-2024-code-for-govtech-932803?lb=7gWXVfKv) and any further queries can be taken up on our [Discord channel](https://discord.com/invite/VPrXf7Jxpr) titled DMP queries. Here's a [Video Tutorial](https://youtu.be/nMW-nD8WzHY) on how to submit a proposal for a project.

**Comment by tdaly61** [comment]
hi @AieshaShetty , @NEGRAH-S Can I suggest you join the c4gt-mojafos-2024 channel on the Mifos slack and also look at https://github.com/openMF/mojafos.  best regards

**Comment by NEGRAH-S** [comment]
@tdaly61  okh sir

**Comment by abhinavkumar1122** [comment]
Hi @tdaly61  I am totally interested on working on this project as I am working on this tech stack for around 2 years and I wanted to include all my experience by helping in this project.

**Comment by tdalylextego** [comment]
> Hi @tdaly61 I am totally interested on working on this project as I am working on this tech stack for around 2 years and I wanted to include all my experience by helping in this project.

G'Day @abhinavkumar1122 , this is great, can I ask you to please join the c4gt-mojafos-2024 slack channel on the Mifos slack and say hi.  thanks and regards  Tom

**Comment by tdalylextego** [comment]
> Hi @tdaly61 I am totally interested on working on this project as I am working on this tech stack for around 2 years and I wanted to include all my experience by helping in this project.

G'Day @abhinavkumar1122 , this is great, can I ask you to please join the c4gt-mojafos-2024 slack channel on the Mifos slack and say hi. thanks and regards Tom

**Comment by tdaly61** [comment]
> Hi @tdaly61 I am totally interested on working on this project as I am working on this tech stack for around 2 years and I wanted to include all my experience by helping in this project.

G'Day @abhinavkumar1122 , this is great, can I ask you to please join the c4gt-mojafos-2024 slack channel on the Mifos slack and say hi. thanks and regards Tom

**Comment by yashsharma127** [comment]
# Weekly Learnings & Updates (To be filled by contributor)  

## Week 1 (Research Week) 

- **Exploring the Project Repository**: Explored the project repository and worked towards understanding the project architecture. Spent time understanding the Helm deployment configurations and how they are structured within the project.  

- **Kubernetes Operators**: Explored the core concepts and architecture of Kubernetes Operators. Understood the importance of Operators in managing the lifecycle of Kubernetes applications and the key components like Custom Resource Definitions (CRDs) and Controllers. 

- **Creation Methods for Kubernetes Operators**: Researched various design patterns for building robust Kubernetes Operators, explored different ways to create K8 Operators i.e. Go, Helm, and Ansible based K8 Operators.

- **Kubernetes Concepts**: Worked towards learning and refreshing Kubernetes concepts, including pods, deployments, services, and config maps. Reinforced understanding of Kubernetes architecture and best practices for managing containerized applications. 

## Week 2 

## Week 3 

## Week 4

**Comment by DavidH-1** [comment]
Replaced by https://github.com/openMF/mifos-operators/issues/1 this ticket is now closed.
