### ISSUE TITLE
[DMP 2024]: Performance Testing Tool/Harness for Monthly Costing & TCO of PH-EE

### ISSUE THREAD

**Issue by DavidH-1** [openMF/ph-ee-env-labs#263]
## Description
The institutions that need to deploy Payment Hub EE to connect into inclusive instant payment systems like Mojaloop or to connect into mobile money APIs are resource-constrained and need to optimize the cost of deploying Payment Hub EE as much as possible. This project would center around building out a bundled performance testing tool and harness to project and monitor monthly costs and overall total cost of ownership. 

## Goals

- [1] [Determine the design of the environment to generate performance test load]
- [2] [Implement environment (likely jMeter) and ship as a container to generated load against PH-EE or Mobile Wallet (exact details to come from Mojafos work]
- [3] [Enable environment to generate reports that give a broad input for the cost estimation tools for the popular cloud platforms such as GCP.  ]
- [4] [Enable the environment to also automatically deploy and configure monitoring tools (grafana/prometheus)]
- [5] [Create roadmap for future scope of project to easily deploy to non-Mojafos and Mifos/PH-EE deployments as focus of this project is deploying tool against Mojafos. ]
- [6] [Performance testing tool and harness to analyze costs of using PH-EE]

### Expected Outcome

Cost and Resource-constrained implementers will have better visiblity and control over costs of deploying valuabe tools like PH-EE

### Implementation Details

Performance Testing Tool/Harness to Optimize Cost of PH-EE

Tech Skills Needed
Docker, Kubernetes, Jenkins, Bash, Java - Spring, PostgreSQL, MariaDB, Cassandra, TDD With JUnit 4, Gradle

### Product Name

Performance Testing Tool/Harness to Optimize Cost of PH-EE

### Organisation Name

The Mifos Initiative

### Domain

Financial Inclusion

### Tech Skills Needed

Docker, Java, Jenkins, Kubernetes, Spring Boot, Other

### Mentor(s)

@tdaly61

### Category

Backend, CI/CD, Delpoyment, Other

**Comment by AieshaShetty** [comment]
Hi @tdaly61, I would like to work on this project. My tech stack includes core Java, Spring Boot, and JPA. Is there any smaller issue to work on this first?

**Comment by AbhimanyuSamagra** [comment]
Do not ask process related questions about how to apply and who to contact in the above ticket. The only questions allowed are about technical aspects of the project itself. If you want help with the process, you can refer instructions listed on [Unstop](https://unstop.com/competitions/dedicated-mentoring-program-dmp-2024-code-for-govtech-932803?lb=7gWXVfKv) and any further queries can be taken up on our [Discord channel](https://discord.com/invite/VPrXf7Jxpr) titled DMP queries. Here's a [Video Tutorial](https://youtu.be/nMW-nD8WzHY) on how to submit a proposal for a project.

**Comment by DavidH-1** [comment]
THIS ISSUE HAS BEEN MIGRATED TO THE MOJAFOS REPO https://github.com/openMF/mojafos/issues/44
